### ISSUE TITLE
hostsがアップデートされない

### ISSUE THREAD

**Issue by pyama86** [pyama86/vaz#2]
```
登録してるHostsがアップデートされずに
増殖してしまうのですが、設定の不備等ありますでしょうか？

トークンはホスト毎に分けて登録してあります。
よろしくお願いいたします。
```
@ykkuii

こちらでログなどいただけると助かります！ちなみにトークンはホストごとに別けて登録する必要はありません！

**Comment by ykkuii** [comment]
ご連絡頂きありがとうございます！
当該ログとキャプチャをお送りいたします。
※ログは1ホストのみ添付

また、トークンについても了解いたしました。
増殖の原因がトークンかと思い分けて登録してみました。

お手数おかけいたしますが、
何卒よろしくお願いいたします。

**Comment by pyama86** [comment]
どうもメールからの返信だとgithubのissueに画像など送られなさそうですね。
ログ、キャプチャをこちらに張っていただけると助かります！

**Comment by ykkuii** [comment]
失礼いたしました。
ご確認下さいませ。

[vaz.log-20171125.zip](https://github.com/pyama86/vaz/files/1504730/vaz.log-20171125.zip)

![veeta](https://user-images.githubusercontent.com/16700319/33251481-373c9470-d37a-11e7-9a24-f5bdb4ef7b9e.png)

**Comment by pyama86** [comment]
`"{\"message\":\"Not Acceptable\"} http request error"` とでているのでtoken周りが何か問題ありそうですね。ちょっと後でDB見てみますね。

**Comment by pyama86** [comment]
こちらについて、ホスト登録後、何かしらのエラーで更新がエラーになった場合に起こりえる挙動でした。対応後リリースします。

**Comment by pyama86** [comment]
0.0.5で修正されました。
